import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/** navigation bar */}
        <div className="flex justify-around items-center bg-gray-100 p-5">
          <Link href="/" className="text-gray-800">
            ホーム
          </Link>
          <form>
            <input className="border border-black m-1" type="text" />
            <input
              className="border border-black text-black"
              type="submit"
              value="🔍"
            />
          </form>
          <Link href="/login" className="text-gray-800">
            ログイン
          </Link>
          <Link href="/join" className="text-gray-800">
            会員登録
          </Link>
        </div>
        <div className="m-4">{children}</div>
        {/** footer */}
        <div className="fixed left-0 bottom-0 w-full bg-gray-100 p-4 text-center text-gray-500">
          @muhyun
        </div>
      </body>
    </html>
  );
}
